W5D1/Shpotify-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]

  resources :bands
  resources :albums
  resources :tracks
end

W5D1/Shpotify-master/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer
#  live       :boolean          default(FALSE)
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  validates_presence_of :title, :band_id

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id,
    primary_key: :id

  has_many :tracks,
    class_name: :Track,
    foreign_key: :album_id,
    primary_key: :id

end

W5D1/Shpotify-master/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates_presence_of :name

  has_many :albums,
    class_name: :Album,
    foreign_key: :band_id,
    primary_key: :id

  has_many :tracks,
    through: :albums,
    source: :tracks
end

W5D1/Shpotify-master/app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint(8)        not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
end

W5D1/Shpotify-master/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  ord        :integer
#  lyrics     :text
#  bonus      :boolean          default(FALSE)
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord

  validates_presence_of :title, :album_id

  belongs_to :album,
    class_name: :Album,
    foreign_key: :album_id,
    primary_key: :id

  has_one :band,
    through: :album,
    source: :band


end

W5D1/Shpotify-master/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
   
class User < ApplicationRecord
  attr_reader :password
  validates :email, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token

  def self.find_by_credentials(email,pw)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(pw)
    user
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(password_digest).is_password?(pw)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

W5D1/Shpotify-master/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash[:error] = @album.errors.full_messages
      redirect_to new_album_url
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash[:error] = @album.errors.full_messages
      redirect_to edit_album_url
    end
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end

end

W5D1/Shpotify-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :auth_token, :current_user, :logged_in?

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!(user)
    session[:session_token] = nil
    user.reset_session_token!
  end
end

W5D1/Shpotify-master/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:error] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:error] = @band.errors.full_messages
      redirect_to edit_band_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

W5D1/Shpotify-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create

    @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:error] = 'User credentials invalid'
      # redirect_to songs_url
      redirect_to new_session_url
    end
  end

  def destroy
    logout!(current_user)
    redirect_to new_session_url
  end
end

W5D1/Shpotify-master/app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

W5D1/Shpotify-master/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash[:error] = @track.errors.full_messages
      redirect_to new_track_url
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash[:error] = @track.errors.full_messages
      redirect_to edit_track_url
    end
  end

  private
  def track_params
    params.require(:track).permit(:title, :ord, :album_id, :lyrics, :bonus)
  end
end

W5D1/Shpotify-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

    if @user
      render :show
    else
      # redirect_to :root
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,:password)
  end
end

W5D1/Shpotify-master/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/Shpotify-master/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/Shpotify-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/Shpotify-master/app/helpers/tags_helper.rb
module TagsHelper
end

W5D1/Shpotify-master/app/helpers/tracks_helper.rb
module TracksHelper
end

W5D1/Shpotify-master/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/Shpotify-master/app/views/albums/_album.html.erb
<h2> <%= album.title %> by <%= link_to album.band.name, band_url(album.band) %></h2>

<label for="year">Recorded year:</label>
<h3> <%= album.year %> </h3>

<label for="live">Recorded in studio or live?:</label>
<h3> <%= album.live ? 'Live' : 'Studio' %> </h3>

<label> <h2>Tracks</h2> </label>
<ol>
<% album.tracks.sort_by{|t|t.ord}.each do |track| %>
  <li> <%= link_to track.title, track_url(track)%>
    <%= '*Bonus Track!*' if track.bonus %></li>
<% end %>
</ol>

W5D1/Shpotify-master/app/views/albums/_form.html.erb
<% if action == :new %>
  <% action_url = albums_url  %>
  <% submit_text = 'Create!' %>
<% end %>

<% if action == :edit %>
  <% action_url = album_url(album)  %>
  <% submit_text = 'Edit!' %>
<% end %>

<form  action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>
  <label for="band">Recording Artist</label>
  <select id='band' name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value=<%= band.id %>
        <%= 'selected' if album.band_id == band.id%> >
        <%= band.name %></option>
    <% end %>
  </select>

  <label for="title">Album Title:</label>
  <input class='form' id='title' type="text" name="album[title]" value=' <%= album.title %> '>

  <label for="year">Year:</label>
  <input id='year' type="text" name="album[year]" value=" <%= album.year %> ">

  <label for='live'>Live or studio recording?</label>
  <input id='live' type="radio" name="album[live]" value="TRUE" <%= 'checked if album && album.live' %> > Live
  <br>
  <input id='live' type="radio" name="album[live]" value="FALSE" <%= 'checked' if album && !album.live %> > Studio

  <input class = 'form' type="submit" value="<%= submit_text %>">

</form>

W5D1/Shpotify-master/app/views/albums/edit.html.erb
<h1> 🥁 Edit this album! 🎷</h1>

<%= render 'form', action: :edit, album: @album %>

W5D1/Shpotify-master/app/views/albums/index.html.erb
<h1> 🎼 All The Albums! 🎸 </h1>

<div>  <%= link_to 'Create new album', new_album_url %> </div>


<ul>
<% @albums.each do |album| %>
  <li class='index_band'><%= link_to "#{album.title} by #{album.band.name}", album_url(album) %></li>
<% end %>
</ul>

W5D1/Shpotify-master/app/views/albums/new.html.erb
<h1>💿Create your album!💽</h1>

<%= render 'form', action: :new, album: @album %>

W5D1/Shpotify-master/app/views/albums/show.html.erb
<br>
<% track = Track.new(album_id: @album.id) %>
<div><%= link_to 'All Albums!', albums_url %><%= link_to 'edit this album', edit_album_url(@album) %> <%= link_to 'Add track to album!', new_track_url %> </div>
<%= render 'album', album: @album %>

W5D1/Shpotify-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🎵MusicApp🎵</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://fonts.googleapis.com/css?family=Annie Use Your Telescope' rel='stylesheet'>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <header class='header'>
  <marquee>  <h1 class='welcome'>🎵Welcome to Shpootify🎵</h1></marquee>
    <% if logged_in? %>
      <h2 class='login_status'>Welcome 🎭<%= current_user.email %> 🎭</h2>
      <div>
        <%= link_to 'Profile page', user_url(current_user) %>
        <%= link_to 'Home', bands_url %>
        <%= link_to 'Albums', albums_url %>
        <%= link_to 'Tracks', tracks_url %>

      </div>
      <%= button_to 'Sign out', session_url, method: :delete, class: :logout%>
    <% else %>
      <div>
        <%= link_to 'Sign in', new_session_url, class: :signin %>
        <%= link_to 'Sign up!', new_user_url, class: :signin %>
        <br>
        <%= link_to 'Home', bands_url %>
        <%= link_to 'Albums', albums_url %>
      </div>
    <% end %>
  </header>
  <body>


    <%= yield %>
  </body>
</html>

W5D1/Shpotify-master/app/views/tracks/_form.html.erb
<% if action == :new %>
  <% action_url = tracks_url  %>
  <% submit_text = 'Create!' %>
<% end %>

<% if action == :edit %>
  <% action_url = track_url(track)  %>
  <% submit_text = 'Edit!' %>
<% end %>


<form id='track' action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>
  <label for="album">Album</label>
  <select id='album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option value=<%= album.id %>
        <%= 'selected' if track.album_id == album.id%> >
        <%= album.title %></option>
    <% end %>
  </select>

  <label for="title">Track Title:</label>
  <input class='form' id='title' type="text" name="track[title]" value=' <%= track.title %> '>

  <label>Track no.</label>
  <input type="text" name="track[ord]" value=" <%= track.ord %> ">

  <input type="checkbox" name="track[bonus]" value="true" <%='checked' if track && track.bonus %> >Bonus Track?<br>

  <label>Lyrics</label>
  <textarea name="track[lyrics]" form="track"> <%= track.lyrics %> </textarea>

  <input class = 'form' type="submit" value="<%= submit_text %>">

</form>

W5D1/Shpotify-master/app/views/tracks/_track.html.erb
<h2> <%= track.title %> by
   <%= link_to track.album.band.name, band_url(track.album.band) %>
   from album: <%=link_to track.album.title, album_url(track.album)%>
 </h2>

<label for="title">Track name:</label>
<h3> <%= track.title %> </h3>


<h3>Track no. <%=track.ord%></h3>

<h3><%= 'Bonus Track' if track.bonus %></h3>

<label>lyrics</label>
<h3> <%= track.lyrics%> </h3>

W5D1/Shpotify-master/app/views/tracks/edit.html.erb
<h1> 🥁 Edit this track! 🎷</h1>

<%= render 'form', action: :edit, track: @track %>

W5D1/Shpotify-master/app/views/tracks/index.html.erb
<h1> 🎼 All The Tracks! 🎸 </h1>

<div>  <%= link_to 'Create new track', new_track_url %> </div>


<ul>
<% @tracks.each do |track| %>
  <li class='index_band'><%= link_to "#{track.title} by #{track.album.band.name}", track_url(track) %></li>
<% end %>
</ul>

W5D1/Shpotify-master/app/views/tracks/new.html.erb
<h1>🛤Add your track!🛤</h1>

<%= render 'form', action: :new, track: @track %>

W5D1/Shpotify-master/app/views/tracks/show.html.erb
<br>
<div><%= link_to 'All Tracks!', tracks_url %><%= link_to 'edit this track', edit_track_url(@track) %></div>
<%= render 'track', track: @track %>

W5D1/Shpotify-master/app/views/users/_form.html.erb
<% if action == :new %>
  <% action_url = users_url  %>
  <% submit_text = 'Sign up' %>
<% end %>

<% if action == :login %>
  <% action_url = session_url  %>
  <% submit_text = 'Login' %>
<% end %>

<form  action="<%= action_url %>" method="post">

  <%= auth_token %>

  <label for="email">email</label>
  <input class='form' id='email' type="text" name="user[email]">

  <label for="password">password</label>
  <input class ='form' type="password" name="user[password]">
  <input class = 'form' type="submit" value="<%= submit_text %>">

</form>

W5D1/Shpotify-master/app/views/users/new.html.erb
<h1>Sign up</h1>
<% if !flash[:error].nil? %>
  <% flash[:error].each do |error| %>
    <li class='error'> <%= error %> </li>
  <% end %>
<% end %>
<%= render 'form', action: :new, user: @user %>

W5D1/Shpotify-master/app/views/users/show.html.erb
<h1> <%= @user.email %></h1>